services:
  postgres:
    image: postgres:16.2-alpine
    container_name: postgres_auth
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "auth" ]
      interval: 10s
      timeout: 10s
      retries: 5
